### ISSUE TITLE
Create disks around source and target for fast queries.

### ISSUE THREAD

**Issue by PatrickOHara** [alan-turing-institute/urbanroute#10]
**Is your feature request related to a problem? Please describe.**
We are given 
- a source and target vertex
- a (hex)grid
- the road network

Problem: run a geospatial query to cut down the size of the road network, rathar than querying the whole network

**Describe the solution you'd like**

1. Calculate the haversine distance $d$ between source and target.
2. For both source and target, create a disk of radius $d$.
3. Compute the geospatial intersection between the two disks and the road network.
4. If we are worried about removing possible solution, take the convex hull of the two disks and then comptue intersection.

**Describe alternatives you've considered**

Returning the whole road network is big query and returns lots of wasted data.

**Additional context**

**Comment by JamesCraster** [comment]
I think the answer is an ellipse, I'm not sure which ellipse though:
[Ellipse drawing](https://en.wikipedia.org/wiki/Ellipse#/media/File:Ellipse-def-e.svg)
The focus points of an ellipse are such that all points p on the edge of the ellipse have the same total distance from A to p + distance from p to B, which is the property we would like, we just need to set that distance ourselves in some way.

**Comment by JamesCraster** [comment]
There are two conference papers on the subject:
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.58.4351&rep=rep1&type=pdf
and
https://link.springer.com/chapter/10.1007/11753728_49 (paywalled, unfortunately)
This kind of geospatial pruning has impact on algorithm running time as well as query time, I would imagine.

**Comment by JamesCraster** [comment]
We need to find an empirical value tau, that determines how big our ellipse should be to have high probability of containing the optimal path.

**Comment by JamesCraster** [comment]
I've created a branch ellipses, I think my ellipse drawing is correct, this leaves the database requests + tau value to do.
[Example ellipse+bounding box](https://imgur.com/a/wHH2pSK)

**Comment by PatrickOHara** [comment]
This is done
