### ISSUE TITLE
Obtain all simple paths in graph, so we can plot them and determine tradeoff between pollution and distance.

### ISSUE THREAD

**Issue by JamesCraster** [alan-turing-institute/urbanroute#19]
Solution will likely rely upon `nx.all_simple_paths(G,source,target)`

**Comment by PatrickOHara** [comment]
Good spot using `all_simple_paths`. Gives us an easy way to enumerate our solution space.

I guess we need to be careful about choosing our source and target vertices. Ideally we should repeat this for 10 randomly chosen pairs of (source, target) to avoid any weird anomalies in the AQ model.

**Comment by JamesCraster** [comment]
Yep, we can use `choice` in Python for that. https://stackoverflow.com/questions/26768065/how-to-extract-random-nodes-from-networkx-graph

**Comment by JamesCraster** [comment]
It looks like I mistakenly deleted the most relevant sourcefile in a separate PR, so I need to make another PR for this.

**Comment by JamesCraster** [comment]
Likely unnecessary as we have now switched to graph-tools and implemented mospp
