### ISSUE TITLE
Multi-objective shortest path

### ISSUE THREAD

**Issue by PatrickOHara** [alan-turing-institute/urbanroute#23]
Optimise both air pollution and social distancing.

**Implementation**
- [ ] James - increase size of elipse and ensure we aren't missing solutions
- [ ] Patrick - find another variable to optimise (road width, traffic, pavement width)
- [ ] James - implement basic Martin's paper. Exponential but a good starting point for future enhancements
- [ ] Patrick - implement pre-processing method for nodes
- [ ] James - implementing A* heuristic for Martin's

**Research**
- [x] James & Patrick - look into existin GA algorithms for connecting solutions and how they handle the mutations
- [ ] Patrick - connectivty encoding in existing literature for ML/graph theory
- [x] Patrick - can a IP be relaxed to a linear program to get an approximation of the Pareto front?
- [ ] James - can we use approximation scheme. How good is it with real-world data?

**Comment by JamesCraster** [comment]
Modifying the size of the ellipse can be performed by increasing tau in ellipses.py. it is initially set to 1.1 (so all paths at most 10% longer than the shortest path are allowed). I think the idea here is to increase the size of the ellipse and check if the Pareto front is not greatly increased in width? However this depends on the variable to optimise, and given the factorially many paths we cannot make the ellipse too large. With pollution density vs length, it appears that increasing the ellipse size (within computational limits) doesn't increase the front width.

**Comment by JamesCraster** [comment]
There is a paper on relaxing the integer program to a linear program for MOSPP: A parametric approach to solving bicriterion
shortest path problems, I've cited it in the overleaf document.
